### ISSUE TITLE
Add pagination to the "HOME" page to speed up rendering times

### ISSUE THREAD

**Issue by lukezsmith** [0xTranqui/Finders-Fee-Finder#1]
Hi!

Came across your project on twitter and wanted to see if I could help at all so I had a go at the pagination feature and got a basic implementation working that looks like below:
![2022-06-01 11 22 57](https://user-images.githubusercontent.com/41703507/171383829-eb903470-15fe-4be4-bb96-4a9e3a276e42.gif)

Basic sorting and page navigation is working fine currently, just need to fix search functionality

**Comment by lukezsmith** [comment]
Issue fix implemented in PR #2

**Comment by 0xTranqui** [comment]
Just left a comment with small update before merging. Also, can you explain more regarding "fixing" the serach functionality? At the moment it only allows for specific token lookup, so no pagination should be required? Or are you saying that you are working on expanding the search functionality to make it more flexibile? Thanks for your help!

**Comment by lukezsmith** [comment]
> Just left a comment with small update before merging. Also, can you explain more regarding "fixing" the serach functionality? At the moment it only allows for specific token lookup, so no pagination should be required? Or are you saying that you are working on expanding the search functionality to make it more flexibile? Thanks for your help!

The comment re: fixing search functionality was when I was running into trouble with the feed not updating after searching  which I managed to fix, sorry I should have clarified before submitting the PR. Currently, the pagination component is still visible (with 1 page) if a result is found, and the same is true even if there are no results found. I can see how this may be undesirable so if you want, I can change it so that the pagination is hidden in both of these cases. Let me know!

**Comment by 0xTranqui** [comment]
> 

ah got it. umm maybe just hide it if no results? and then this is good to go I think!
